"""Add daily activity tables

Revision ID: 99a6981b6313
Revises: 46f28580381f
Create Date: 2025-11-06 21:44:18.392796

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '99a6981b6313'
down_revision: Union[str, Sequence[str], None] = '46f28580381f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_file_activity',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('daily_activity_id', sa.Integer(), nullable=False),
    sa.Column('entity', sa.String(), nullable=False),
    sa.Column('project', sa.String(), nullable=True),
    sa.Column('total_seconds', sa.Integer(), nullable=True),
    sa.Column('total_line_changes', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['daily_activity_id'], ['daily_activity.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_daily_file_activity_id'), 'daily_file_activity', ['id'], unique=False)
    op.create_table('daily_language_activity',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('daily_activity_id', sa.Integer(), nullable=False),
    sa.Column('language', sa.String(), nullable=False),
    sa.Column('total_seconds', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['daily_activity_id'], ['daily_activity.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_daily_language_activity_id'), 'daily_language_activity', ['id'], unique=False)
    op.create_table('daily_project_activity',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('daily_activity_id', sa.Integer(), nullable=False),
    sa.Column('project_name', sa.String(), nullable=False),
    sa.Column('total_seconds', sa.Integer(), nullable=True),
    sa.Column('files_edited', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['daily_activity_id'], ['daily_activity.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_daily_project_activity_id'), 'daily_project_activity', ['id'], unique=False)
    op.add_column('daily_activity', sa.Column('total_files_edited', sa.Integer(), nullable=True))
    op.add_column('daily_activity', sa.Column('total_projects', sa.Integer(), nullable=True))
    op.add_column('daily_activity', sa.Column('total_languages', sa.Integer(), nullable=True))
    op.add_column('daily_activity', sa.Column('created_at', sa.TIMESTAMP(), nullable=True))
    op.alter_column('daily_activity', 'date',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.Date(),
               existing_nullable=False)
    op.create_index(op.f('ix_daily_activity_date'), 'daily_activity', ['date'], unique=False)
    op.drop_column('daily_activity', 'project_worked_on')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('daily_activity', sa.Column('project_worked_on', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_daily_activity_date'), table_name='daily_activity')
    op.alter_column('daily_activity', 'date',
               existing_type=sa.Date(),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.drop_column('daily_activity', 'created_at')
    op.drop_column('daily_activity', 'total_languages')
    op.drop_column('daily_activity', 'total_projects')
    op.drop_column('daily_activity', 'total_files_edited')
    op.drop_index(op.f('ix_daily_project_activity_id'), table_name='daily_project_activity')
    op.drop_table('daily_project_activity')
    op.drop_index(op.f('ix_daily_language_activity_id'), table_name='daily_language_activity')
    op.drop_table('daily_language_activity')
    op.drop_index(op.f('ix_daily_file_activity_id'), table_name='daily_file_activity')
    op.drop_table('daily_file_activity')
    # ### end Alembic commands ###
