"""update heartbeat model fields

Revision ID: ef551f7e997e
Revises: b46d8b4a3ab8
Create Date: 2025-11-03 22:53:20.083150

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ef551f7e997e'
down_revision: Union[str, Sequence[str], None] = 'b46d8b4a3ab8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('heartbeats', sa.Column('alternate_project', sa.String(), nullable=True))
    op.add_column('heartbeats', sa.Column('project_folder', sa.String(), nullable=True))
    op.add_column('heartbeats', sa.Column('project_root_count', sa.Integer(), nullable=True))
    op.add_column('heartbeats', sa.Column('lines_in_file', sa.Integer(), nullable=True))
    op.add_column('heartbeats', sa.Column('line_changes', sa.Integer(), nullable=True))
    op.add_column('heartbeats', sa.Column('is_unsaved_entity', sa.Boolean(), nullable=True))
    op.drop_column('heartbeats', 'lines')
    op.drop_column('heartbeats', 'project')
    op.drop_column('heartbeats', 'type')
    op.drop_column('heartbeats', 'branch')
    op.drop_column('heartbeats', 'category')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('heartbeats', sa.Column('category', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('heartbeats', sa.Column('branch', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('heartbeats', sa.Column('type', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('heartbeats', sa.Column('project', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('heartbeats', sa.Column('lines', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('heartbeats', 'is_unsaved_entity')
    op.drop_column('heartbeats', 'line_changes')
    op.drop_column('heartbeats', 'lines_in_file')
    op.drop_column('heartbeats', 'project_root_count')
    op.drop_column('heartbeats', 'project_folder')
    op.drop_column('heartbeats', 'alternate_project')
    # ### end Alembic commands ###
